### ISSUE TITLE
unexpected keyword argument 'include_body'

### ISSUE THREAD

**Issue by kakachiex2** [kijai/ComfyUI-MimicMotionWrapper#1]
I got this error wen executing the node

Downloading yolo model to: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\models\DWPose
Fetching 1 files: 100%|██████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.11it/s]
Downloading dwpose model to: K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\models\DWPose
Fetching 1 files: 100%|██████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.27it/s]
!!! Exception during processing!!! draw_pose() got an unexpected keyword argument 'include_body'
Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 317, in process
    im = draw_pose(detected_pose, height, width, include_body=include_body, include_hand=include_hand, include_face=include_face)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: draw_pose() got an unexpected keyword argument 'include_body'

**Comment by kijai** [comment]
Hmm must be some conflict with the imports, possibly fixed now, if you could try updating and running again.

**Comment by kakachiex2** [comment]
Ok let me try

**Comment by kakachiex2** [comment]
Its working know I let you know when it finishes

**Comment by kakachiex2** [comment]
I get this error finishing the process I'm surprise that the video almost finish looks like you optimized the wrapper very well
my RTX260 is only 6gb of VRam.
 
Error occurred when executing MimicMotionSampler:

Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated : 4.42 GiB
Requested : 2.25 GiB
Device limit : 6.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
: 17179869184.00 GiB

File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 199, in process
frames = pipeline(
^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 648, in __call__
frames = self.decode_latents(latents, num_frames, decode_chunk_size)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 266, in decode_latents
frame = self.vae.decode(latents[i: i + decode_chunk_size], **decode_kwargs).sample
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
return method(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_temporal_decoder.py", line 364, in decode
decoded = self.decoder(z, num_frames=num_frames, image_only_indicator=image_only_indicator)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\models\autoencoders\autoencoder_kl_temporal_decoder.py", line 147, in forward
sample = up_block(sample, image_only_indicator=image_only_indicator)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\models\unets\unet_3d_blocks.py", line 1874, in forward
hidden_states = upsampler(hidden_states)
^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\diffusers\models\upsampling.py", line 183, in forward
hidden_states = self.conv(hidden_states)
^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
return self._conv_forward(input, self.weight, self.bias)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "K:\ComfyUI\ComfyUI_Ex\python_miniconda_env\ComfyUI\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
return F.conv2d(input, weight, bias, self.stride,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Cndkrsn10** [comment]
i got same error,  draw_pose() got an unexpected keyword argument 'include_body'

**Comment by mrkennypowers** [comment]
I had the error and after a fresh install it worked again. Its very likely a confict with another node.

**Comment by Cndkrsn10** [comment]
nice just reinstall, running now

**Comment by kijai** [comment]
> I get this error finishing the process I'm surprise that the video almost finish looks like you optimized the wrapper very well my RTX260 is only 6gb of VRam.
> 
> Error occurred when executing MimicMotionSampler:
> 
> Allocation on device 0 would exceed allowed memory. (out of memory) Currently allocated : 4.42 GiB Requested : 2.25 GiB Device limit : 6.00 GiB Free (according to CUDA): 0 bytes PyTorch limit (set by user-supplied memory fraction) : 17179869184.00 GiB

It could potentially work if you decode it frame by frame, by default the number was 8. I have now separated the decode phase to make it cleared and added the option to adjust the chunk size:

![image](https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/40791699/c9cccc86-9108-41cc-93e7-92dd03c3df57)
