### ISSUE TITLE
Error occurred when executing MimicMotionGetPoses :object of type 'NoneType’ has no len()

### ISSUE THREAD

**Issue by KANKANYANGKANKAN** [kijai/ComfyUI-MimicMotionWrapper#29]
![QQ截图20240709155350](https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/169335809/cfcfb172-2112-4696-ba40-1c45091a0e5a)

**Comment by 771991673** [comment]
same

**Comment by kijai** [comment]
Sorry but these error reports with so little info are pretty much useless, need to know the workflow, selected model, python environment versions, full  startup log etc. etc.

**Comment by gladmustang** [comment]
Kijai, I encounter same issue, from my check ,I find if the video file incllude some blank frame that may  could not figure out the the person, then this error may happen, you can see the frame below that cause this error.
![image](https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/8908241/291cf698-ea08-4b2c-9169-2f2c55b21ffc)

**Comment by dwgeneral** [comment]
@kijai occurred same issue, and here is the context: 

- error stack info:
```
2024-07-10 14:14:34,169- root:124- INFO- Prompt executed in 0.10 seconds
2024-07-10 14:17:20,567- root:450- INFO- got prompt
[rgthree] Using rgthree's optimized recursive execution.
2024-07-10 14:17:20,982- root:179- ERROR- !!! Exception during processing!!! object of type 'NoneType' has no len()
2024-07-10 14:17:20,982- root:180- ERROR- Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper/nodes.py", line 427, in process
    detected_poses_np_list.append(self.dwprocessor(img_np))
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper/mimicmotion/dwpose/dwpose_detector.py", line 29, in __call__
    candidate, score = self.pose_estimation(oriImg)
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper/mimicmotion/dwpose/wholebody.py", line 38, in __call__
    keypoints, scores = inference_jit_pose(self.pose, det_result, oriImg)
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper/mimicmotion/dwpose/jit_pose.py", line 357, in inference_pose
    resized_img, center, scale = preprocess(oriImg, out_bbox, model_input_size)
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper/mimicmotion/dwpose/jit_pose.py", line 25, in preprocess
    if len(out_bbox) == 0:
TypeError: object of type 'NoneType' has no len()
```

- workflow file:  examples/mimic_motion_example_02.json
![Screenshot 2024-07-10 at 2 17 35 PM](https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/8654993/f27d82ae-2d21-4444-8c65-6177cd4ee6fd)


- model: 
![Screenshot 2024-07-10 at 2 29 54 PM](https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/8654993/33eae017-f2df-4b50-9e6e-675bc46eea7f)

python env:
- Python 3.10.13
[pip_list.txt](https://github.com/user-attachments/files/16156311/pip_list.txt)

**Comment by dwgeneral** [comment]
I have raised a pr to fix this issue, and it's worked for me.

**Comment by piovis2023** [comment]
@dwgeneral what did you do to fix this mate?

I just used the example workflow from the repo, but reorganised it to learn how it works - however, I'm getting the same error.

My setup:
Windows 11 OS
Non-portable version of comfyui (re-installed today so all up to date)
Python 3.10
Cuda 1.2.1

<img width="1037" alt="image" src="https://github.com/kijai/ComfyUI-MimicMotionWrapper/assets/130514657/bb920e2f-763f-4345-93ab-4ac9e899dfbf">

**Comment by kijai** [comment]
> @dwgeneral what did you do to fix this mate?
> 
> I just used the example workflow from the repo, but reorganised it to learn how it works - however, I'm getting the same error.
> 
> My setup: Windows 11 OS Non-portable version of comfyui (re-installed today so all up to date) Python 3.10 Cuda 1.2.1
> 
> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/130514657/347467534-bb920e2f-763f-4345-93ab-4ac9e899dfbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjU2NzAsIm5iZiI6MTcyMDYyNTM3MCwicGF0aCI6Ii8xMzA1MTQ2NTcvMzQ3NDY3NTM0LWJiOTIwZTJmLTc2M2YtNDM0NS05M2FiLTRhYzllODk5ZGZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxNTI5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMThlZTY3ZGVhN2I2ZDAzNTgyMmQxMzcxMDhkZGRhMWFhYWUwZDFlMDI3OTVkZjBiNTZkZjY5YWYyNDBjZmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._dHwGNrqE9djVtxJccwp3UQ_sSlGmyPtqNapBQ5_phw">

Try with the included example assets first to make sure it's not a detection issue or some other issue with your source, they are in the custom node's folder: assets\example_data\videos

**Comment by dwgeneral** [comment]
> @dwgeneral what did you do to fix this mate?
> 
> I just used the example workflow from the repo, but reorganised it to learn how it works - however, I'm getting the same error.
> 
> My setup: Windows 11 OS Non-portable version of comfyui (re-installed today so all up to date) Python 3.10 Cuda 1.2.1
> 
> <img alt="image" width="1037" src="https://private-user-images.githubusercontent.com/130514657/347467534-bb920e2f-763f-4345-93ab-4ac9e899dfbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODAzMzIsIm5iZiI6MTcyMDY4MDAzMiwicGF0aCI6Ii8xMzA1MTQ2NTcvMzQ3NDY3NTM0LWJiOTIwZTJmLTc2M2YtNDM0NS05M2FiLTRhYzllODk5ZGZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwNjQwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODUwYzAxNTM5ZTNmYzRiNmMxMmFjZDkwN2ZiYjM5NmRjYWYzYzI0YjE2Yzc0NzExMDc0ODE4NmU3MTI2Zjc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5HuR9YdpKSESxElJ0yqAIPZPJzBC3i6fVQNjKsBxRqI">

You can git pull the latest code for this repo and restart your ComfyUI to try it, and you should follow the steps that @kijai said above

**Comment by piovis2023** [comment]
Thank you @dwgeneral and @kijai I'll try it out and update the luck/no-luck update here.
