### ISSUE TITLE
Error when using the example workflow

### ISSUE THREAD

**Issue by popovidis** [kijai/ComfyUI-MimicMotionWrapper#41]
```
!!! Exception during processing!!! name 'is_accelerate_available' is not defined
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-MimicMotionWrapper/nodes.py", line 115, in loadmodel
    with (init_empty_weights() if is_accelerate_available else nullcontext()):
NameError: name 'is_accelerate_available' is not defined
```

**Comment by wolverinex24** [comment]
same issue i am facing any solution or explanation

**Comment by kijai** [comment]
That's probably from having too old diffusers version

**Comment by kijai** [comment]
Or actually its from not having accelerate installed, either install that (recommended) or update these nodes and it shouldn't be necessary, just slower model loading

**Comment by wolverinex24** [comment]
i updated the comfyui and python_dependencies it's  fixed  now thankyou
just run this its inside update folder
update_comfyui_and_python_dependencies.bat
