### ISSUE TITLE
getting  NameError: name 'is_accelerate_available' is not defined

### ISSUE THREAD

**Issue by wolverinex24** [kijai/ComfyUI-MimicMotionWrapper#45]
getting this i tried uninstalling and installing again but didn't rn on my machine 
help me with cause or give me direction  I can try to solve this 
error is like that :
got prompt
Loading model from: W:\ComfyUI_windows_portable\ComfyUI\models\mimicmotion\MimicMotionMergedUnet_1-0-fp16.safetensors
Loading UNET
!!! Exception during processing!!! name 'is_accelerate_available' is not defined
Traceback (most recent call last):
  File "W:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 116, in loadmodel
    with (init_empty_weights() if is_accelerate_available else nullcontext()):
                                  ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'is_accelerate_available' is not defined

**Comment by wolverinex24** [comment]
![Screenshot 2024-07-13 021338](https://github.com/user-attachments/assets/f5b8b728-4e81-48dd-9287-7a917904eba1)

**Comment by wolverinex24** [comment]
this fixed by doing proper reinstallation and maintaining this folder structure properly  name by name 
as already mentioned in readme section 

─feature_extractor
│       preprocessor_config.json
│
├───image_encoder
│       config.json
│       model.fp16.safetensors
│
├───scheduler
│       scheduler_config.json
│
├───unet
│       config.json
│       diffusion_pytorch_model.fp16.safetensors
│
└───vae
        config.json
        diffusion_pytorch_model.fp16.safetensors
