### ISSUE TITLE
TypeError: retrieve_timesteps() takes from 1 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by kotaxyz** [kijai/ComfyUI-MimicMotionWrapper#7]
Thanks for your hard work ! i get this error i have rtx 3060ti 8gb vram 

got prompt
[rgthree] Using rgthree's optimized recursive execution.
num_frames:  16
torch.Size([16, 320, 128, 72])
doing classifier free guidance
!!! Exception during processing!!! retrieve_timesteps() takes from 1 to 4 positional arguments but 5 were given
Traceback (most recent call last):
  File "I:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "I:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "I:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 297, in process
    frames = pipeline(
  File "I:\ComfyUI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 570, in __call__
    timesteps, num_inference_steps = retrieve_timesteps(self.scheduler, num_inference_steps, device, None, sigmas)
TypeError: retrieve_timesteps() takes from 1 to 4 positional arguments but 5 were given

**Comment by kijai** [comment]
> i have watched the video in description , it seems it takes +12gb vram so i guess its a vram limitation issue !

Nah, you can get away with much less VRAM if you just lower the resolution. That error message is because you have too old diffusers version.
