### ISSUE TITLE
Error occurred when executing DownloadAndLoadMimicMotionModel!!!!!!

### ISSUE THREAD

**Issue by goodluck821** [kijai/ComfyUI-MimicMotionWrapper#81]
ot prompt
Loading model from: J:\ComfyUI-aki-v1.4.7\models\mimicmotion\MimicMotionMergedUnet_1-0-fp16.safetensors
Loading UNET
Loading VAE
Loading IMAGE_ENCODER
Loading POSE_NET
!!! Exception during processing !!! The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/fx/graph_module/___torch_mangle_1305.py", line 966, in forward
    _7 = (Slice_39).forward(onnx_initializer_30, onnx_initializer_31, onnx_initializer_28, onnx_initializer_29, _6, )
    _8 = (Concat_40).forward(_1, _5, _3, _7, )
    _9 = (Conv_41).forward(_8, )
          ~~~~~~~~~~~~~~~~ <--- HERE
    _10 = (Mul_43).forward(_9, (Sigmoid_42).forward(_9, ), )
    _11 = (Conv_44).forward(_10, )
  File "code/__torch__/torch/nn/modules/conv/___torch_mangle_877.py", line 12, in forward
    bias = self.bias
    weight = self.weight
    input = torch._convolution(argument_1, weight, bias, [1, 1], [1, 1], [1, 1], False, [0, 0], 1, False, False, True, True)
            ~~~~~~~~~~~~~~~~~~ <--- HERE
    return input

Traceback of TorchScript, original code (most recent call last):
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py(456): _conv_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py(460): forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1508): _slow_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1527): _call_impl
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
<eval_with_key>.1(46): forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1508): _slow_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1527): _call_impl
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py(274): __call__
/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py(678): call_wrapped
/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py(1065): trace_module
/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py(798): trace
<ipython-input-4-4b9aca434064>(8): <cell line: 8>
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3553): run_code
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3473): run_ast_nodes
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3257): run_cell_async
/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py(78): _pseudo_sync_runner
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3030): _run_cell
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(2975): run_cell
/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py(539): run_cell
/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py(302): do_execute
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(539): execute_request
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(261): dispatch_shell
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(361): process_one
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(786): run
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(825): inner
/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py(738): _run_callback
/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py(685): <lambda>
/usr/lib/python3.10/asyncio/events.py(80): _run
/usr/lib/python3.10/asyncio/base_events.py(1909): _run_once
/usr/lib/python3.10/asyncio/base_events.py(603): run_forever
/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py(195): start
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py(619): start
/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py(992): launch_instance
/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py(37): <module>
/usr/lib/python3.10/runpy.py(86): _run_code
/usr/lib/python3.10/runpy.py(196): _run_module_as_main
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

Traceback (most recent call last):
  File "J:\ComfyUI-aki-v1.4.7\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "J:\ComfyUI-aki-v1.4.7\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "J:\ComfyUI-aki-v1.4.7\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "J:\ComfyUI-aki-v1.4.7\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "J:\ComfyUI-aki-v1.4.7\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 412, in process
    ref_pose = self.dwprocessor(ref_image)
  File "J:\ComfyUI-aki-v1.4.7\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\dwpose\dwpose_detector.py", line 29, in __call__
    candidate, score = self.pose_estimation(oriImg)
  File "J:\ComfyUI-aki-v1.4.7\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\dwpose\wholebody.py", line 37, in __call__
    det_result = inference_jit_yolox(self.det, oriImg, detect_classes=[0])
  File "J:\ComfyUI-aki-v1.4.7\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\dwpose\jit_det.py", line 105, in inference_detector
    output = model(input).float().cpu().detach().numpy()
  File "J:\ComfyUI-aki-v1.4.7\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "J:\ComfyUI-aki-v1.4.7\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/fx/graph_module/___torch_mangle_1305.py", line 966, in forward
    _7 = (Slice_39).forward(onnx_initializer_30, onnx_initializer_31, onnx_initializer_28, onnx_initializer_29, _6, )
    _8 = (Concat_40).forward(_1, _5, _3, _7, )
    _9 = (Conv_41).forward(_8, )
          ~~~~~~~~~~~~~~~~ <--- HERE
    _10 = (Mul_43).forward(_9, (Sigmoid_42).forward(_9, ), )
    _11 = (Conv_44).forward(_10, )
  File "code/__torch__/torch/nn/modules/conv/___torch_mangle_877.py", line 12, in forward
    bias = self.bias
    weight = self.weight
    input = torch._convolution(argument_1, weight, bias, [1, 1], [1, 1], [1, 1], False, [0, 0], 1, False, False, True, True)
            ~~~~~~~~~~~~~~~~~~ <--- HERE
    return input

Traceback of TorchScript, original code (most recent call last):
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py(456): _conv_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py(460): forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1508): _slow_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1527): _call_impl
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
<eval_with_key>.1(46): forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1508): _slow_forward
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1527): _call_impl
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py(1518): _wrapped_call_impl
/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py(274): __call__
/usr/local/lib/python3.10/dist-packages/torch/fx/graph_module.py(678): call_wrapped
/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py(1065): trace_module
/usr/local/lib/python3.10/dist-packages/torch/jit/_trace.py(798): trace
<ipython-input-4-4b9aca434064>(8): <cell line: 8>
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3553): run_code
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3473): run_ast_nodes
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3257): run_cell_async
/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py(78): _pseudo_sync_runner
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(3030): _run_cell
/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py(2975): run_cell
/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py(539): run_cell
/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py(302): do_execute
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(539): execute_request
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(261): dispatch_shell
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(234): wrapper
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py(361): process_one
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(786): run
/usr/local/lib/python3.10/dist-packages/tornado/gen.py(825): inner
/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py(738): _run_callback
/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py(685): <lambda>
/usr/lib/python3.10/asyncio/events.py(80): _run
/usr/lib/python3.10/asyncio/base_events.py(1909): _run_once
/usr/lib/python3.10/asyncio/base_events.py(603): run_forever
/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py(195): start
/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py(619): start
/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py(992): launch_instance
/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py(37): <module>
/usr/lib/python3.10/runpy.py(86): _run_code
/usr/lib/python3.10/runpy.py(196): _run_module_as_main
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR


Prompt executed in 5.04 seconds
![屏幕截图 2024-10-20 160243](https://github.com/user-attachments/assets/44b3188d-77bf-4994-9bf3-fd980d14c40d)
![屏幕截图 2024-10-20 160452](https://github.com/user-attachments/assets/962d2a52-70d9-4862-a68f-79fca4989952)

**Comment by goodluck821** [comment]
![屏幕截图 2024-10-20 161358](https://github.com/user-attachments/assets/8c585066-1f2a-4684-99af-94244c366fe0)

**Comment by goodluck821** [comment]
自从升级到现在后，comfyui_controlnet_aux集成中的dwpose, mimicmotiond的dwpose和ControlNeXt-SVD的dwpose都不能用了，只有独立dwpose在不用dw-ll_ucoco_384_bs5.torchscript和yolox_l.torchscript模型，才能正常运行使用，说明这两个模型有兼容性问题，请作者修改一下。

**Comment by goodluck821** [comment]
ComfyUI-MimicMotionWrapper太折磨人啦，我想放弃torch依赖，改为onnx依赖，请大佬们指教，怎么说修改nodes.py。torch版本的兼容平台太差了。
