### ISSUE TITLE
matplotlib version

### ISSUE THREAD

**Issue by sanyi2-zhang** [kijai/ComfyUI-MimicMotionWrapper#83]
Hello, I would like to ask about the issue with the version of matplotlib. I encountered the following problem while running the workflow, and I suspect it is a version issue with matplotlib. If possible, please let me know。

# ComfyUI Error Report
## Error Details
- **Node Type:** MimicMotionGetPoses
- **Exception Type:** ModuleNotFoundError
- **Exception Message:** No module named 'matplotlib'
## Stack Trace
```
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 382, in process
    from .mimicmotion.dwpose.util import draw_pose

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\dwpose\util.py", line 3, in <module>
    import matplotlib

```
## System Information
- **ComfyUI Version:** v0.2.6
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1660 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 6442123264
  - **VRAM Free:** 5370806272
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-07 00:45:38,549 - root - INFO - Total VRAM 6144 MB, total RAM 16262 MB
2024-11-07 00:45:38,549 - root - INFO - pytorch version: 2.5.0+cu124
2024-11-07 00:45:38,564 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-07 00:45:38,564 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1660 : cudaMallocAsync
2024-11-07 00:45:39,650 - root - INFO - Using pytorch cross attention
2024-11-07 00:45:40,934 - root - INFO - [Prompt Server] web root: D:\comfyui\ComfyUI_windows_portable\ComfyUI\web
2024-11-07 00:45:41,360 - root - INFO - Total VRAM 6144 MB, total RAM 16262 MB
2024-11-07 00:45:41,360 - root - INFO - pytorch version: 2.5.0+cu124
2024-11-07 00:45:41,360 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-07 00:45:41,360 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1660 : cudaMallocAsync
2024-11-07 00:45:43,685 - root - INFO - 
Import times for custom nodes:
2024-11-07 00:45:43,685 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-07 00:45:43,685 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-11-07 00:45:43,685 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-07 00:45:43,685 - root - INFO -    0.1 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Transformers
2024-11-07 00:45:43,685 - root - INFO -    0.1 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-07 00:45:43,685 - root - INFO -    0.2 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper
2024-11-07 00:45:43,685 - root - INFO -    0.2 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-07 00:45:43,685 - root - INFO -    0.3 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-07 00:45:43,685 - root - INFO -    1.5 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-07 00:45:43,685 - root - INFO - 
2024-11-07 00:45:43,685 - root - INFO - Starting server

2024-11-07 00:45:43,685 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-07 00:45:45,764 - root - INFO - got prompt
2024-11-07 00:45:47,542 - root - ERROR - !!! Exception during processing !!! No module named 'matplotlib'
2024-11-07 00:45:47,543 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 382, in process
    from .mimicmotion.dwpose.util import draw_pose
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\dwpose\util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

2024-11-07 00:45:47,545 - root - INFO - Prompt executed in 1.70 seconds
2024-11-07 01:00:45,727 - root - INFO - got prompt
2024-11-07 01:00:46,321 - root - ERROR - !!! Exception during processing !!! No module named 'matplotlib'
2024-11-07 01:00:46,323 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 382, in process
    from .mimicmotion.dwpose.util import draw_pose
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\dwpose\util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'

2024-11-07 01:00:46,325 - root - INFO - Prompt executed in 0.49 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":58,"last_link_id":151,"nodes":[{"id":9,"type":"GetImageSizeAndCount","pos":{"0":825,"1":518},"size":{"0":210,"1":86},"flags":{},"order":6,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":112}],"outputs":[{"name":"image","type":"IMAGE","links":[148],"slot_index":0,"shape":3},{"name":"width","type":"INT","links":null,"shape":3},{"name":"height","type":"INT","links":null,"shape":3},{"name":"count","type":"INT","links":null,"shape":3}],"properties":{"Node name for S&R":"GetImageSizeAndCount"},"widgets_values":[]},{"id":42,"type":"MimicMotionGetPoses","pos":{"0":327,"1":702},"size":{"0":330,"1":126},"flags":{},"order":5,"mode":0,"inputs":[{"name":"ref_image","type":"IMAGE","link":110},{"name":"pose_images","type":"IMAGE","link":111}],"outputs":[{"name":"poses_with_ref","type":"IMAGE","links":[112,114],"slot_index":0,"shape":3},{"name":"pose_images","type":"IMAGE","links":[138],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"MimicMotionGetPoses"},"widgets_values":[true,true,true]},{"id":28,"type":"ImageResizeKJ","pos":{"0":-71,"1":481},"size":{"0":315,"1":242},"flags":{},"order":3,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":61},{"name":"get_image_size","type":"IMAGE","link":null,"shape":7},{"name":"width_input","type":"INT","link":null,"widget":{"name":"width_input"}},{"name":"height_input","type":"INT","link":null,"widget":{"name":"height_input"}}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[95,110,147],"slot_index":0,"shape":3},{"name":"width","type":"INT","links":[88],"slot_index":1,"shape":3},{"name":"height","type":"INT","links":[89],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"ImageResizeKJ"},"widgets_values":[576,1024,"lanczos",true,64,0,0,"disabled"]},{"id":17,"type":"ImageConcatMulti","pos":{"0":1644,"1":830},"size":{"0":210,"1":190},"flags":{},"order":10,"mode":0,"inputs":[{"name":"image_1","type":"IMAGE","link":95},{"name":"image_2","type":"IMAGE","link":137},{"name":"image_3","type":"IMAGE","link":138},{"name":"image_4","type":"IMAGE","link":151}],"outputs":[{"name":"images","type":"IMAGE","links":[93],"slot_index":0,"shape":3}],"properties":{},"widgets_values":[4,"right",false,null]},{"id":37,"type":"VHS_VideoCombine","pos":{"0":678,"1":897},"size":{"0":440,"1":238},"flags":{},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":114,"shape":7},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"MimicPose","format":"image/webp","pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"MimicPose_00006.webp","subfolder":"","type":"temp","format":"image/webp","frame_rate":8}}}},{"id":57,"type":"MimicMotionSampler","pos":{"0":1101,"1":419},"size":{"0":315,"1":430},"flags":{},"order":8,"mode":0,"inputs":[{"name":"mimic_pipeline","type":"MIMICPIPE","link":146},{"name":"ref_image","type":"IMAGE","link":147},{"name":"pose_images","type":"IMAGE","link":148},{"name":"optional_scheduler","type":"DIFFUSERS_SCHEDULER","link":null,"shape":7}],"outputs":[{"name":"samples","type":"LATENT","links":[149],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"MimicMotionSampler"},"widgets_values":[20,2,2,42,"fixed",15,0,16,6,false,1,0,1,1]},{"id":35,"type":"ImageResizeKJ","pos":{"0":-75,"1":781},"size":{"0":315,"1":242},"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":86},{"name":"get_image_size","type":"IMAGE","link":null,"shape":7},{"name":"width_input","type":"INT","link":88,"widget":{"name":"width_input"}},{"name":"height_input","type":"INT","link":89,"widget":{"name":"height_input"}}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[111,137],"slot_index":0,"shape":3},{"name":"width","type":"INT","links":null,"shape":3},{"name":"height","type":"INT","links":null,"shape":3}],"properties":{"Node name for S&R":"ImageResizeKJ"},"widgets_values":[576,1024,"lanczos",false,64,0,0,"disabled"]},{"id":3,"type":"LoadImage","pos":{"0":-393,"1":311},"size":{"0":213.0849151611328,"1":410.70074462890625},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[61],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["3fc15960ef9615defaed12c407892fe.png","image"]},{"id":5,"type":"VHS_LoadVideo","pos":{"0":-402,"1":787},"size":[235.1999969482422,491.1999969482422],"flags":{},"order":1,"mode":0,"inputs":[{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[86],"slot_index":0,"shape":3},{"name":"frame_count","type":"INT","links":null,"shape":3},{"name":"audio","type":"AUDIO","links":null,"shape":3},{"name":"video_info","type":"VHS_VIDEOINFO","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_LoadVideo"},"widgets_values":{"video":"Gradio.mp4","force_rate":0,"force_size":"Disabled","custom_width":512,"custom_height":512,"frame_load_cap":15,"skip_first_frames":0,"select_every_nth":2,"choose video to upload":"image","videopreview":{"hidden":false,"paused":false,"params":{"frame_load_cap":15,"skip_first_frames":0,"force_rate":0,"filename":"Gradio.mp4","type":"input","format":"video/mp4","select_every_nth":2}}}},{"id":58,"type":"MimicMotionDecode","pos":{"0":1466,"1":396},"size":{"0":255.466796875,"1":78},"flags":{},"order":9,"mode":0,"inputs":[{"name":"mimic_pipeline","type":"MIMICPIPE","link":150,"slot_index":0},{"name":"samples","type":"LATENT","link":149}],"outputs":[{"name":"images","type":"IMAGE","links":[151],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"MimicMotionDecode"},"widgets_values":[4]},{"id":2,"type":"DownloadAndLoadMimicMotionModel","pos":{"0":658,"1":230},"size":{"0":404.8147277832031,"1":89.03937530517578},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"mimic_pipeline","type":"MIMICPIPE","links":[146,150],"shape":3}],"properties":{"Node name for S&R":"DownloadAndLoadMimicMotionModel"},"widgets_values":["MimicMotionMergedUnet_1-1-fp16.safetensors","fp16"]},{"id":16,"type":"VHS_VideoCombine","pos":{"0":1867,"1":146},"size":[2861.660400390625,310],"flags":{},"order":11,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":93,"shape":7},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":12,"loop_count":0,"filename_prefix":"MimicMotion","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"MimicMotion_00002.mp4","subfolder":"","type":"temp","format":"video/h264-mp4","frame_rate":12}}}}],"links":[[61,3,0,28,0,"IMAGE"],[86,5,0,35,0,"IMAGE"],[88,28,1,35,2,"INT"],[89,28,2,35,3,"INT"],[93,17,0,16,0,"IMAGE"],[95,28,0,17,0,"IMAGE"],[110,28,0,42,0,"IMAGE"],[111,35,0,42,1,"IMAGE"],[112,42,0,9,0,"IMAGE"],[114,42,0,37,0,"IMAGE"],[137,35,0,17,1,"IMAGE"],[138,42,1,17,2,"IMAGE"],[146,2,0,57,0,"MIMICPIPE"],[147,28,0,57,1,"IMAGE"],[148,9,0,57,2,"IMAGE"],[149,57,0,58,1,"LATENT"],[150,2,0,58,0,"MIMICPIPE"],[151,58,0,17,3,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.3310000000000004,"offset":[-3475.3238456004315,-46.56188677734995]}},"version":0.4}

thanks

**Comment by kijai** [comment]
It's saying you don't have matplotlib installed at all.

**Comment by sanyi2-zhang** [comment]
> It's saying you don't have matplotlib installed at all.

thanks,I have already solved this problem
