### ISSUE TITLE
macbook - 报这个错： Error no file named diffusion_pytorch_model.fp16.bin found

### ISSUE THREAD

**Issue by kuanglijun** [kijai/ComfyUI-MimicMotionWrapper#88]
!!! Exception during processing !!! Error no file named diffusion_pytorch_model.fp16.bin found in directory /Users/xxxx/Documents/comfyui/ComfyUI-New/models/diffusers/stable-video-diffusion-img2vid-xt-1-1.
Traceback (most recent call last):
  File "/Users/xxxx/Documents/comfyui/ComfyUI-New/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Documents/comfyui/ComfyUI-New/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Documents/comfyui/ComfyUI-New/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/xxxx/Documents/comfyui/ComfyUI-New/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/Documents/comfyui/ComfyUI-New/custom_nodes/ComfyUI-MimicMotionWrapper/nodes.py", line 131, in loadmodel
    self.vae = AutoencoderKLTemporalDecoder.from_pretrained(svd_path, subfolder="vae", variant="fp16", low_cpu_mem_usage=True).to(dtype).to(device).eval()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/anaconda3/envs/comfyui-312/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/anaconda3/envs/comfyui-312/lib/python3.12/site-packages/diffusers/models/modeling_utils.py", line 804, in from_pretrained
    model_file = _get_model_file(
                 ^^^^^^^^^^^^^^^^
  File "/Users/xxxx/anaconda3/envs/comfyui-312/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/anaconda3/envs/comfyui-312/lib/python3.12/site-packages/diffusers/utils/hub_utils.py", line 309, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.fp16.bin found in directory /Users/xxxx/Documents/comfyui/ComfyUI-New/models/diffusers/stable-video-diffusion-img2vid-xt-1-1.

**Comment by kuanglijun** [comment]
文件名我改错了
